import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import React, { ReactText, useState } from 'react';

interface IUser {
  name?: string;
  email: string;
}

function LoadingSpinner() {
  return (
    <div className={styles.spinnerContainer}>
      <div className={styles.loadingSpinner}>
      </div>
    </div>
  );
}


const Home: NextPage = () => {
  const [lead, setLead] = useState <IUser>({email: ''});
  const [isLoading, setIsLoading] = useState(false);

  const handleChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
    setLead({email: event.target.value});
  }

  const handleChangeName = (event: React.ChangeEvent<HTMLInputElement>) => {
    setLead({
      ...lead,
      name: event.target.value
    });
  }

  const sendLeadToLL = (event: React.FormEvent <HTMLFormElement>) => {
    setIsLoading(true);
    event.preventDefault()
    {/* 645018 MachineCode */}
    {/* 50415 EmailSequenceCode */}
    {/* 2AB28B2F633B4AEB8DD5DC92D824B532 Api Token */}
    {/* http://llapi.leadlovers.com/webapi/ Base Url */}

    axios.post('http://llapi.leadlovers.com/webapi/Lead?token=2AB28B2F633B4AEB8DD5DC92D824B532', {
      MachineCode: '645018',
      EmailSequenceCode: 50415,
      SequenceLevelCode: 1,
      Email: lead.email,
      Name: lead.name
    })
    .then(function (response) {
      console.log(response);
      setIsLoading(false)
    })
    .catch(function (error) {
      console.error(error);
    });
  }
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Analytics Summit - O maior evento de anlytics da América Latina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:locale" content="pt_BR"/>
        <meta property="og:site_name" content="Analytics Summit"/>
        <meta property="og:title" content="Analytics Summit - O maior evento de Web Analytics do Brasil"/>
        <meta property="og:url" content="https://analyticssummit.com.br" />
        <meta property="og:image" content="/og-image-min.png" />
        <meta property="og:image:type" content="image/png"/>
        <meta property="og:image:width" content="1369" /> 
        <meta property="og:image:height" content="604" /> 
        <meta property="og:description" content="Reunimos os melhores especialistas do mercado em uma jornada repleta de dicas e insights, proporcionando uma imersão total no incrível mundo do web analytics, indo desde seus fundamentos até as estratégias mais avançadas." />
        <meta property="og:type" content="website" />
        <link rel="stylesheet" href="//paginas.rocks/Content/capture/forms/formCustom.css" />
        
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <section className={styles.contentArea}>
            <header className={styles.header}>
              <Image src="/logo-summit.png" width={232} height={60} />
            </header>
            <h1 className={styles.title}>
              O maior evento de Analytics <br/> da América Latina está chegando
            </h1>
            <p className={styles.description}>
              O Analytics Summit em 2021 alcançou mais de 25.000+ pessoas e empresas, em 2022 teremos a segunda edição do maior evento sobre Digital Analytics da América Latina.
            </p>
            <p className={styles.description}>
              O evento acontecerá nos dias 22 e 23 de agosto e contará com inúmeras palestras e mesas redondas com quem entende do mercado.
            </p>
          </section>
          <section className={styles.formArea}>

            <form id="llCaptureForm" className={`llformCustom ${styles.form}`} onSubmit={sendLeadToLL}>
              <h2>Inscreva-se agora</h2>
              <input type="hidden" id="mid" name="mid" value="645018" />
              <input type="hidden" id="fid" name="fid" value="50415" />
              <input type="hidden" id="formType" name="formType" value="dynamic" />
              <div>
                  <label className={styles.label} htmlFor={"llfield73387"}>Nome</label>
                  <input type="text" id="llfield73387" onChange={handleChangeName} name="llfield73387" placeholder="Primeiro Nome" />
                  <div className="field-error" id="llerror73387"></div>
              </div>
              <div>
                  <label className={styles.label} htmlFor="llfield73385">Informe o seu melhor e-mail</label>
                  <input type="email" onChange={handleChangeEmail} id="llfield73385" name="llfield73385" placeholder="Digite o seu melhor e-mail" data-required="true" />
                  <div className="field-error" id="llerror73385"></div>
              </div>
              <div>
                  <div className="field-error" id="LGPDValidation"></div>
                  <div className="checkbox-list" data-required="true" >
                      <div className="checkbox">
                          <label>
                              <input type="checkbox" id="LGPDValidation" name="LGPDValidation" value="1" /> Sim, desejo receber e-mails sobre artigos, noticias, tendências ou ofertas. O consentimento pode ser retirado a qualquer momento clicando no link de cancelamento de inscrição presente em todas as comunicações por e-mail.
                          </label>
                      </div>
                  </div>
              </div>
              <div className={`button-bar ${styles.buttonBar}`}>
                  <button className={styles.buttonSignUp} disabled={isLoading} type="submit">Quero me cadastrar</button>
                  {isLoading && <LoadingSpinner />}
              </div>
            </form>
          </section>
        </div>
      </main>
    </div>
  )
}

export default Home
